apiVersion: v1
kind: Service
metadata:
  name: metadata-db
  labels:
    app.kubernetes.io/name: metadata-db
    app.kubernetes.io/instance: metadata-db-manual
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: metadata-db
    app.kubernetes.io/instance: metadata-db-manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-db
  labels:
    app.kubernetes.io/name: metadata-db
    app.kubernetes.io/instance: metadata-db-manual
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: metadata-db
      app.kubernetes.io/instance: metadata-db-manual
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metadata-db
        app.kubernetes.io/instance: metadata-db-manual
    spec:
      containers:
        - name: metadata-db
          image: "madhuakula/k8s-goat-metadata-db:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
